name: CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - name: Run Node.js security audit
      run: npm audit --audit-level=high
    - run: npm test

  cleanup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Remove unnecessary files
      run: |
        rm -rf node_modules
        npm cache clean --force
